"""
backend/app/db/base.py
-----------------------
Re-exports Base for Alembic's env.py.

Alembic needs to import Base (which holds all table metadata) from a
stable path.  This file is that stable path — it imports Base from
core/database.py and also imports all models so their tables are
registered with Base.metadata before Alembic reads it.

If a model is NOT imported here, Alembic will not detect its table
and autogenerate migrations will miss it.

Usage in database/migrations/env.py:
    from app.db.base import Base
    target_metadata = Base.metadata
"""

from app.core.database import Base  # noqa: F401  — re-export for Alembic

# Import all models so their tables register with Base.metadata.
# These imports MUST stay here — removing any one causes Alembic
# to silently skip that table in autogenerated migrations.
from app.models.user              import User              # noqa: F401
from app.models.forensic_image    import (                 # noqa: F401
    ForensicImage,
    PreprocessedImage,
    FeatureSet,
    ModelVersion,
)
from app.models.similarity_result import SimilarityResult  # noqa: F401
from app.models.report            import Report            # noqa: F401
from app.models.dataset           import Dataset           # noqa: F401
from app.models.audit_log         import AuditLog          # noqa: F401
from app.models.feedback          import Feedback          # noqa: F401