"""Initial PostgreSQL schema

Revision ID: 01cc3e270e2b
Revises: 001
Create Date: 2026-03-27 15:38:11.564745

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "01cc3e270e2b"
down_revision: Union[str, None] = "001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_users_created_at", table_name="users")
    op.drop_index("idx_users_email", table_name="users")
    op.drop_index("idx_users_email_role", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "full_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column("email", sa.VARCHAR(length=100), autoincrement=False, nullable=False),
        sa.Column(
            "password_hash", sa.VARCHAR(length=200), autoincrement=False, nullable=False
        ),
        sa.Column(
            "role",
            postgresql.ENUM("analyst", "admin", "ai_engineer", name="user_role_enum"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "badge_number", sa.VARCHAR(length=50), autoincrement=False, nullable=True
        ),
        sa.Column(
            "department", sa.VARCHAR(length=100), autoincrement=False, nullable=True
        ),
        sa.Column(
            "phone_number", sa.VARCHAR(length=20), autoincrement=False, nullable=True
        ),
        sa.Column("is_active", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column("is_super_admin", sa.BOOLEAN(), autoincrement=False, nullable=True),
        sa.Column(
            "must_change_password", sa.BOOLEAN(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "failed_login_attempts", sa.INTEGER(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "locked_until",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "last_login",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "last_login_ip", sa.VARCHAR(length=45), autoincrement=False, nullable=True
        ),
        sa.Column(
            "preferences",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("created_by", sa.UUID(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name="users_created_by_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="users_pkey"),
        sa.UniqueConstraint(
            "badge_number",
            name="users_badge_number_key",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            "email",
            name="users_email_key",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index("idx_users_email_role", "users", ["email", "role"], unique=False)
    op.create_index("idx_users_email", "users", ["email"], unique=False)
    op.create_index("idx_users_created_at", "users", ["created_at"], unique=False)
    # ### end Alembic commands ###
