/**
 * src/pages/reports.tsx
 * ───────────────────────
 * Forensic PDF reports list page.
 * Shows all reports generated by the current user, newest first.
 * Each row has a one-click PDF download button.
 *
 * Pagination
 * ───────────
 * 20 reports per page. Previous / Next buttons shown when total > 20.
 * Page resets to 1 when navigating away and returning.
 */

import { useState, useEffect } from "react";
import Head   from "next/head";
import Link   from "next/link";
import { FileText, ArrowRight } from "lucide-react";

import AppLayout      from "../components/layout/AppLayout";
import Card           from "../components/ui/Card";
import Button         from "../components/ui/Button";
import Spinner        from "../components/ui/Spinner";
import ReportViewer   from "../components/forensic/ReportViewer";

import { reportService, ReportResponse } from "../services/reportService";

const LIMIT = 20;

export default function ReportsPage() {
  const [reports, setReports] = useState<ReportResponse[]>([]);
  const [total,   setTotal]   = useState(0);
  const [page,    setPage]    = useState(1);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    setLoading(true);
    reportService
      .list({ page, limit: LIMIT })
      .then((res) => {
        setReports(res.reports);
        setTotal(res.total);
      })
      .finally(() => setLoading(false));
  }, [page]);

  const totalPages = Math.ceil(total / LIMIT);

  return (
    <>
      <Head><title>Reports — ForensicEdge</title></Head>

      <AppLayout title="Forensic Reports">

        {/* ── Page header ───────────────────────────────────────────────── */}
        <div className="flex items-end justify-between flex-wrap gap-3">
          <div>
            <h2 className="text-white font-semibold text-lg">Reports</h2>
            <p className="text-gray-500 text-sm mt-0.5">
              {loading ? "Loading…" : `${total} report${total !== 1 ? "s" : ""} generated`}
            </p>
          </div>

          <Link href="/compare">
            <Button
              size="sm"
              icon={<ArrowRight size={14} />}
            >
              New comparison
            </Button>
          </Link>
        </div>

        {/* ── Content ───────────────────────────────────────────────────── */}
        {loading ? (
          <div className="flex justify-center py-16">
            <Spinner size="lg" />
          </div>

        ) : reports.length === 0 ? (
          /* Empty state */
          <Card className="text-center py-16 space-y-4">
            <div className="w-16 h-16 rounded-2xl bg-gray-800 flex items-center
                            justify-center mx-auto">
              <FileText size={28} className="text-gray-600" />
            </div>
            <div>
              <p className="text-gray-300 font-medium">No reports yet</p>
              <p className="text-gray-600 text-sm mt-1">
                Run a comparison and click "Generate PDF Report" to create one.
              </p>
            </div>
            <Link href="/compare">
              <Button size="sm">Start a comparison</Button>
            </Link>
          </Card>

        ) : (
          /* Report list */
          <div className="space-y-3">
            {reports.map((report) => (
              <ReportViewer key={report.id} report={report} />
            ))}
          </div>
        )}

        {/* ── Pagination ────────────────────────────────────────────────── */}
        {totalPages > 1 && (
          <div className="flex items-center justify-center gap-3">
            <Button
              variant="secondary"
              size="sm"
              disabled={page === 1 || loading}
              onClick={() => setPage((p) => p - 1)}
            >
              Previous
            </Button>

            <span className="text-gray-500 text-sm tabular-nums">
              Page {page} of {totalPages}
            </span>

            <Button
              variant="secondary"
              size="sm"
              disabled={page >= totalPages || loading}
              onClick={() => setPage((p) => p + 1)}
            >
              Next
            </Button>
          </div>
        )}

      </AppLayout>
    </>
  );
}