"""
backend/app/main.py
--------------------
ForensicEdge FastAPI application entry point.

Startup sequence (lifespan)
----------------------------
    1. Create storage directories
    2. Create database tables (via db/base.py which registers all models)
    3. Load fingerprint inference engine  (best_model_fingerprint.pth)
    4. Load toolmark inference engine     (best_model_toolmark.pth)
       — skipped with a warning if weights not yet trained

Run locally
-----------
    cd backend
    uvicorn app.main:app --reload --host 0.0.0.0 --port 8000

Run with Docker Compose
-----------------------
    docker-compose up --build

API docs (auto-generated by FastAPI)
--------------------------------------
    Swagger UI : http://localhost:8000/docs
    ReDoc      : http://localhost:8000/redoc
"""
import sys
import os

sys.path.append(os.path.abspath(".."))
from contextlib import asynccontextmanager
from pathlib    import Path

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

from app.core.config   import settings
from app.core.database import engine
from app.db.base       import Base          # imports all models for create_all
from app.utils.logger  import app_logger    # structured logger

from app.api.routes_auth     import router as auth_router
from app.api.routes_upload   import router as upload_router
from app.api.routes_compare  import router as compare_router
from app.api.routes_report   import router as report_router
from app.api.routes_admin    import router as admin_router
from app.api.routes_logs     import router as logs_router
from app.api.routes_feedback import router as feedback_router


# ---------------------------------------------------------------------------
# Lifespan — startup and shutdown
# ---------------------------------------------------------------------------

@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    FastAPI lifespan context manager.
    Code before `yield` runs at startup; code after runs at shutdown.
    """
    # 1. Ensure storage directories exist
    settings.create_storage_dirs()
    app_logger.info("Storage directories ready")

    # 2. Create database tables
    # Base is imported from db/base.py which imports ALL models —
    # no risk of a model being skipped as was possible with inline imports.
    async with engine.begin() as conn:
        await conn.run_sync(Base.metadata.create_all)
    app_logger.info("Database tables created or verified")

    # 3. Load inference engines — one per evidence type
    # Loaded once at startup, reused for all subsequent requests.
    from ai_engine.inference.compare import get_engine

    for evidence_type in ["fingerprint", "toolmark"]:
        weights_attr = f"MODEL_WEIGHTS_PATH_{evidence_type.upper()}"
        weights_path = Path(
            getattr(settings, weights_attr, settings.MODEL_WEIGHTS_PATH)
        )
        if weights_path.exists():
            try:
                get_engine(evidence_type=evidence_type)
                app_logger.info(
                    "Inference engine loaded",
                    extra={"evidence_type": evidence_type},
                )
            except Exception as e:
                app_logger.warning(
                    "Could not load inference engine",
                    extra={"evidence_type": evidence_type, "error": str(e)},
                )
        else:
            app_logger.warning(
                "Model weights not found — train the model first",
                extra={
                    "evidence_type": evidence_type,
                    "weights_path":  str(weights_path),
                },
            )

    app_logger.info(
        f"{settings.APP_NAME} API ready",
        extra={"prefix": settings.API_V1_PREFIX, "docs": "/docs"},
    )

    yield  # application runs here

    app_logger.info(f"{settings.APP_NAME} shutting down")


# ---------------------------------------------------------------------------
# FastAPI application
# ---------------------------------------------------------------------------

app = FastAPI(
    title       = settings.APP_NAME,
    description = (
        "AI-assisted forensic evidence analysis API. "
        "Supports fingerprint and toolmark image comparison using "
        "a Siamese neural network."
    ),
    version     = "1.0.0",
    docs_url    = "/docs",
    redoc_url   = "/redoc",
    lifespan    = lifespan,
)


# ---------------------------------------------------------------------------
# CORS middleware
# ---------------------------------------------------------------------------

app.add_middleware(
    CORSMiddleware,
    allow_origins     = settings.ALLOWED_ORIGINS,
    allow_credentials = True,
    allow_methods     = ["*"],
    allow_headers     = ["*"],
)


# ---------------------------------------------------------------------------
# Routers — all prefixed with /api/v1
# ---------------------------------------------------------------------------

PREFIX = settings.API_V1_PREFIX

app.include_router(auth_router,     prefix=PREFIX)
app.include_router(upload_router,   prefix=PREFIX)
app.include_router(compare_router,  prefix=PREFIX)
app.include_router(report_router,   prefix=PREFIX)
app.include_router(admin_router,    prefix=PREFIX)
app.include_router(logs_router,     prefix=PREFIX)
app.include_router(feedback_router, prefix=PREFIX)


# ---------------------------------------------------------------------------
# Root endpoint
# ---------------------------------------------------------------------------

@app.get("/", tags=["Root"])
async def root():
    """API root — confirms the service is running."""
    return {
        "service": settings.APP_NAME,
        "version": "1.0.0",
        "status":  "running",
        "docs":    "/docs",
    }