"""
backend/app/api/routes_report.py
----------------------------------
Forensic PDF report generation and download endpoints.

Endpoints
---------
    POST /api/v1/reports                     — generate PDF report
    GET  /api/v1/reports                     — list reports
    GET  /api/v1/reports/{report_id}         — get report metadata
    GET  /api/v1/reports/{report_id}/download — download PDF file
"""

from fastapi import APIRouter, Depends, Request, status
from fastapi.responses import FileResponse
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.database     import get_db
from app.core.dependencies import CurrentUser
from app.schemas.report_schema import (
    ReportCreate,
    ReportResponse,
    ReportListResponse,
)
from app.services import report_service
from app.services.log_service import create_log

router = APIRouter(prefix="/reports", tags=["Forensic Reports"])


# ---------------------------------------------------------------------------
@router.post(
    "",
    response_model = ReportResponse,
    status_code    = status.HTTP_201_CREATED,
    summary        = "Generate a forensic PDF report",
)
async def generate_report(
    payload:      ReportCreate,
    request:      Request,
    current_user: CurrentUser  = Depends(),
    db:           AsyncSession = Depends(get_db),
):
    """
    Generate a downloadable PDF forensic report from a similarity result.

    The PDF includes:
    - Evidence images (query + reference, original + enhanced)
    - Similarity percentage and match status (colour-coded)
    - All three metrics (similarity%, cosine, euclidean distance)
    - Evidence type (fingerprint | toolmark)
    - Analyst notes (optional)
    - Professional disclaimer for courtroom use

    One report per similarity result — returns HTTP 409 if already generated.
    """
    return await report_service.generate_report(
        payload    = payload,
        user       = current_user,
        db         = db,
        ip_address = request.client.host if request.client else None,
    )


# ---------------------------------------------------------------------------
@router.get(
    "",
    response_model = ReportListResponse,
    summary        = "List generated reports",
)
async def list_reports(
    page:         int          = 1,
    limit:        int          = 20,
    current_user: CurrentUser  = Depends(),
    db:           AsyncSession = Depends(get_db),
):
    """
    List all forensic reports generated by the current user.
    Admins see all users' reports.
    """
    return await report_service.list_reports(
        user  = current_user,
        db    = db,
        page  = page,
        limit = limit,
    )


# ---------------------------------------------------------------------------
@router.get(
    "/{report_id}",
    response_model = ReportResponse,
    summary        = "Get report metadata",
)
async def get_report(
    report_id:    int,
    current_user: CurrentUser  = Depends(),
    db:           AsyncSession = Depends(get_db),
):
    """Retrieve metadata for a single report including the PDF path."""
    return await report_service.get_report(
        report_id = report_id,
        user      = current_user,
        db        = db,
    )


# ---------------------------------------------------------------------------
@router.get(
    "/{report_id}/download",
    summary = "Download the PDF report file",
)
async def download_report(
    report_id:    int,
    request:      Request,
    current_user: CurrentUser  = Depends(),
    db:           AsyncSession = Depends(get_db),
):
    """
    Download the generated forensic PDF report.

    Returns the PDF file as a binary response with appropriate headers
    for browser download or display.
    """
    pdf_path = await report_service.get_pdf_path(
        report_id = report_id,
        user      = current_user,
        db        = db,
    )

    await create_log(
        db          = db,
        action_type = "report_downloaded",
        user_id     = current_user.id,
        details     = {"report_id": report_id},
        ip_address  = request.client.host if request.client else None,
    )

    return FileResponse(
        path             = str(pdf_path),
        media_type       = "application/pdf",
        filename         = pdf_path.name,
        content_disposition_type = "attachment",
    )